services:
  api:
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production

  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
    environment:
      NODE_ENV: production

  redis:
    image: redis:7
    ports:
      - "6379:6379"